#!/usr/bin/env bash
apt-get update
apt-get -y install nginx
service nginx start
served_by="add_header X-Served-By \$hostname;\n"
sed -i "30i $served_by" /etc/nginx/sites-available/default
service nginx restart