#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but "Hi" if 9

count=0
while [ $count -le 10 ]
do
    if [ $count -eq 9 ]; then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((count++))
done
