#!/usr/bin/env bash
# Installs NGINX on ubuntu
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
redirect_404="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sed -i "30i $redirect_404"  /etc/nginx/sites-available/default
service nginx restart
