#!/usr/bin/env bash
# Resolves local host to 127.0.0.2 and faceboook to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/^127.0.0.2/127.0.0.1/ ~/hosts.new
echo "8.8.8.8" "facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
