#!/usr/bin/env bash
# Script to run nginx as non-root user
default='/etc/nginx/sites-available/default'
conf='/etc/nginx/nginx.conf'
pkill -9 apache2
sed -i 's/80 default_server/8080 default_server/' $default
sed -i 's/#user www-data;/user nginx;/' $conf
service nginx restart